name: Medieval
title: Conquermedieval
description: Conquermedieval de volta.
url: https://cmedieval.github.io/
author: Tim
github: https://github.com/cmedieval/
twitter: Conquermedieval

encoding: utf-8
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
